config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <div id="boxEdit">
    <%= f.check_box :completed %>
    <%= f.label :completed %>
  </div>
  <div class="submit">
    <%= f.submit %>
  </div>
<% end %>

<p><%= link_to 'Go back to Tasks', tasks_path%></p>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
    <% if (task.completed == false) %>
    <i class="fa-regular fa-square"></i>
    <%else%>
    <i class="fa-regular fa-square-check"></i>
    <% end %>
    <%= link_to task.title, task_path(task.id) %>
    <%= link_to task_path(task),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
    🗑️
    <% end %>
    </li>
  <% end %>
</ul>
<p><%= link_to '➕ New task', tasks_new_path%></p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <div class="submit">
    <%= f.submit %>
  </div>
<% end %>

<div class="NewTaskBack">
  <i class="fa-solid fa-arrow-rotate-left"></i>
  <p><%= link_to 'Go back to List', tasks_path%></p>
</div>

app/views/tasks/show.html.erb
<div id="titleSow">
  <h1><%= @task.title %></h1>
  <p id="editButton"><%= link_to '✎ Edit the task', edit_path%></p>
</div>
<p id="detailsShow"><%= @task.details %></p>
<div id="boxShow">
  <% if (@task.completed == true)%>
  <i class="fa-regular fa-square-check"></i>
  This task is completed
  <%else%>
  <i class="fa-regular fa-square"></i>
  This task is not completed yet
  <% end %>
</div>

<p><%= link_to 'Back to the list', tasks_path%></p>